name:                panfeed
version:             0.1.0.0
github:              "githubuser/panfeed"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/panfeed#readme>

dependencies:
- base >= 4.7
- feed
- pandoc

library:
  source-dirs: src
  dependencies:
  - network-uri >= 2.6
  - filepath >= 1.4.2.1
  - text
  - xml-types
  - time
  
executables:
  panfeed:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - panfeed

tests:
  panfeed-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - panfeed
